### ISSUE TITLE
Add support for Maps with enum keys

### ISSUE THREAD

**Issue by fischmax** [Mercateo/rest-schemagen#12]
JSON Hyperschema doesn't allow for keys to be dynamic, so when we have something like

```java
public Map<Foo, Bar> someMap;
```
with example JSON
```js
{
  'key1':'val1',
  'key2':'val2',
}
```
we *cannot* do
```js
{
  'type':'map', /* this doesn't exist )-: */
  'keys': {
    'type':'string',
    'enum': [ 'key1', 'key2' ],
  }
  'values': {
    'type':'string'
  }
}
```
But *iff* the keyset is finite, i.e., for practical reasons, an enum, like
```java
public enum Keys = { KEY_1, KEY_2 };
public Map<Keys, String> someMap;
```
we can do the following:
```js
'someMap': {
  'type':'object',
  'properties': {
    'KEY_1': {
      'type':'string' },
    'KEY_2': {
      'type':'string' },
    },
}
```

Therefore, the SchemaGenerator needs to, when encountering a `Map`, check whether the keyClazz is instanceof Enum and if so, unwind the whole thing. Otherwise it *should* emit `object` and not touch it any further.

**Comment by donaldpipowitch** [comment]
I think this looks good :+1:
